### ISSUE TITLE
Is it possible to have this driver in your nvida repo?

### ISSUE THREAD

**Issue by vpxyz** [negativo17/libva-nvidia-driver#1]
Hi,
would it be possible to have this driver also in your nvidia repository?
Thanks

**Comment by scaronni** [comment]
Unfortunately for the way I've structured things it would need a different `libva`.

Everything in the `nvidia` repository builds with only packages from the main distribution, in the `multimedia` repository there are many rebuilds with possibly newer versions than what is in the main repositories, one of which is `libva` which is a dependency for `nvidia-vaapi-driver`.

Sorry I can't justify the effort for 2 different versions with non-overlapping dependencies.
